import type { Chat } from "@/types/conversation";

export const chats: Chat[] = [
  {
    id: "1",
    name: "Marlin Doe",
    online: true,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 1,
    messages: [
      { id: "m1", sender: "them", text: "Hey! Are we good for tomorrow?", seen: true },
      { id: "m2", sender: "me",   text: "Yep — 10 AM works!",           seen: true },
      { id: "m3", sender: "me", text: "Perfect, see you then.",       seen: true },
      { id: "m4", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m5", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m6", sender: "me", text: "Perfect, see you then.",       seen: true },
      { id: "m7", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m8", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m9", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m10", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m11", sender: "me", text: "Perfect, see you then.",       seen: true },
      { id: "m12", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m13", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m14", sender: "them", text: "Perfect, see you then.",       seen: true },
      { id: "m15", sender: "me", text: "Perfect, see you then.",       seen: true },
      { id: "m16", sender: "them", text: "Perfect, see you then.",       seen: false },
    ],
  },
  {
    id: "2",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "3",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "4",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "5",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "6",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "7",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "8",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "9",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "10",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "11",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "12",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "112",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "1112",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "111112",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "11121",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "211",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "211111",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "21111111111",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
  {
    id: "22124",
    name: "Marlin Doe",
    online: false,
    lastMessage: "Looking forward to seeing you tomorrow",
    unreadCount: 4,
    messages: [
      { id: "m1", sender: "me",   text: "Hello there!",                 seen: true },
      { id: "m2", sender: "them", text: "Got it, thanks!",              seen: false },
      { id: "m3", sender: "them", text: "Also, can we confirm time?",   seen: false },
    ],
  },
];

export const getChatById = (id: string) => chats.find((c) => c.id === id);
